name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Generate Keystore
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          keytool -genkeypair -v \
            -keystore my-upload-key.jks \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias laserbreak \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" \
            -dname "CN=Laserbreak, OU=Android Game, O=AIStudio, L=City, S=State, C=US"
            
      - name: Upload Keystore Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-upload-key.jks
          path: my-upload-key.jks
          retention-days: 1
